import React, { useState, useRef } from 'react';
import { 
  Zap, 
  Sparkles, 
  Download, 
  Printer, 
  FileSpreadsheet, 
  FileText, 
  ShieldCheck, 
  Award, 
  TrendingUp, 
  Users, 
  MapPin, 
  HandCoins, 
  HeartHandshake, 
  GraduationCap, 
  Briefcase, 
  AlertTriangle, 
  MessageSquare, 
  CheckCircle2, 
  Clock, 
  QrCode, 
  ChevronRight, 
  Star,
  Layers,
  PieChart as PieIcon,
  Activity,
  ArrowUpRight,
  BookOpen,
  Cpu,
  Building2,
  Lightbulb,
  FileCheck
} from 'lucide-react';
import * as XLSX from 'xlsx';

export default function SahayataImpactReport() {
  const [period, setPeriod] = useState('30d');
  const reportRef = useRef(null);

  const handleExcelExport = () => {
    const wb = XLSX.utils.book_new();

    const summarySheetData = [
      ['SAHAYATA IMPACT INTELLIGENCE REPORT 2026'],
      ['Reporting Period', 'Last 30 Days (July 2026)'],
      ['Generated Date', new Date().toLocaleString()],
      ['Generated By', 'Sahayata AI Intelligence Engine'],
      [],
      ['Metric Category', 'Key Performance Indicator', 'Value', 'Impact / Growth'],
      ['Workers Empowered', 'Total Registered Workers', '12,450,890', '+18.4% MoM'],
      ['Families Benefited', 'Estimated Family Members Covered', '49,803,560', '4.0 Family Multiplier'],
      ['Financial Inclusion', 'Total Micro-Credit Disbursed', '₹4,825,000,000', '99.2% Repayment Rate'],
      ['Government Reach', 'Government Schemes Accessed', '1,420 Active Schemes', '98.6% Success Rate'],
      ['Insurance Coverage', 'Active Micro-Insurance Policies', '3,200,000 Policies', '99.1% Settlement Ratio'],
      ['Employment Created', 'Successful Job Placements', '118,500 Placements', 'Zomato, Swiggy, L&T'],
      ['AI Guidance', 'AI Voice Assistant Queries', '1,842,109 Conversations', '99.4% AI Accuracy']
    ];
    const ws1 = XLSX.utils.aoa_to_sheet(summarySheetData);
    XLSX.utils.book_append_sheet(wb, ws1, 'Sahayata Impact Summary');

    const workerSheetData = [
      ['Worker Category', 'Total Registered', 'Active Users', 'Verified Users', 'Avg Income Range', 'Growth %'],
      ['Delivery Partners', '4,850,000', '4,510,000', '4,780,000', '₹18,000 - ₹26,000 / mo', '+22.4%'],
      ['Street Vendors', '2,950,000', '2,680,000', '2,890,000', '₹12,000 - ₹18,000 / mo', '+15.2%'],
      ['Construction Labourers', '2,400,000', '2,150,000', '2,320,000', '₹14,000 - ₹20,000 / mo', '+12.8%'],
      ['Domestic Workers', '1,200,000', '1,120,000', '1,180,000', '₹10,000 - ₹15,000 / mo', '+19.5%'],
      ['Farm Labourers', '1,050,000', '920,000', '1,010,000', '₹9,000 - ₹13,000 / mo', '+8.4%']
    ];
    const ws2 = XLSX.utils.aoa_to_sheet(workerSheetData);
    XLSX.utils.book_append_sheet(wb, ws2, 'Worker Sector Analytics');

    XLSX.writeFile(wb, `Sahayata_Impact_Intelligence_Report_${period}.xlsx`);
  };

  const handleCSVExport = () => {
    const csvContent = "data:text/csv;charset=utf-8," 
      + "Metric,Value,Impact\n"
      + "Total Registered Workers,12450890,+18.4% Growth\n"
      + "Families Benefited,49803560,4.0 Multiplier\n"
      + "Disbursed Capital,₹482.5 Cr,99.2% Repayment\n"
      + "AI Voice Conversations,1842109,99.4% Accuracy\n";
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Sahayata_Impact_Report_${period}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handlePrint = () => {
    window.print();
  };

  const workerCategories = [
    { cat: 'Delivery Partners (Zomato/Swiggy)', reg: '4,850,000', active: '4,510,000', verified: '4,780,000', income: '₹18,000 – ₹26,000', growth: '+22.4%', state: 'Maharashtra, Delhi, KA' },
    { cat: 'Street Vendors (QR Merchants)', reg: '2,950,000', active: '2,680,000', verified: '2,890,000', income: '₹12,000 – ₹18,000', growth: '+15.2%', state: 'Gujarat, UP, MH' },
    { cat: 'Construction Labourers', reg: '2,400,000', active: '2,150,000', verified: '2,320,000', income: '₹14,000 – ₹20,000', growth: '+12.8%', state: 'UP, Bihar, MH' },
    { cat: 'Domestic Workers & Artisans', reg: '1,200,000', active: '1,120,000', verified: '1,180,000', income: '₹10,000 – ₹15,000', growth: '+19.5%', state: 'Rajasthan, KA, TN' },
    { cat: 'Farm Labourers', reg: '1,050,000', active: '920,000', verified: '1,010,000', income: '₹9,000 – ₹13,000', growth: '+8.4%', state: 'Punjab, Haryana, MP' }
  ];

  const successStories = [
    {
      name: 'Ramesh Kumar',
      role: 'Zomato Delivery Executive',
      city: 'Mumbai, MH',
      before: 'Income ₹8,000/mo • Unbanked • Zero Insurance',
      after: 'Income ₹22,500/mo • Received ₹15,000 Sachet Loan • Completed EV Fleet Training',
      badge: '3x Income Growth'
    },
    {
      name: 'Sunita Devi',
      role: 'Domestic Worker & Artisan',
      city: 'Lucknow, UP',
      before: 'Income ₹5,000/mo • No Pension Scheme Access',
      after: 'Income ₹14,000/mo • Enrolled in PM-SYM Pension & Micro-Health Insurance',
      badge: 'Social Security Enabled'
    },
    {
      name: 'Vikas Patil',
      role: 'Street Vendor (Snack Stall)',
      city: 'Surat, GJ',
      before: 'Income ₹9,500/mo • High-Interest Moneylender Debt',
      after: 'Income ₹21,000/mo • PM SVANidhi ₹25,000 Loan Approved at 0% Subsidy',
      badge: 'Debt-Free Business Expansion'
    }
  ];

  const impactScores = [
    { title: 'Financial Inclusion Score', score: '99.2 / 100', trend: '+4.2%', reason: '99.2% on-time repayment rate across ₹482.5 Cr disbursed.', rec: 'Expand sachet loan limits to ₹30,000.' },
    { title: 'Employment Support Score', score: '96.8 / 100', trend: '+5.1%', reason: '118,500 successful job placements with Zomato, Swiggy, & L&T.', rec: 'Partner with regional logistics fleets.' },
    { title: 'Government Scheme Reach', score: '98.4 / 100', trend: '+3.8%', reason: '1,420 active schemes matched with 98.4% approval success.', rec: 'Deploy additional rural awareness agents.' },
    { title: 'Worker Welfare Score', score: '97.5 / 100', trend: '+2.9%', reason: '3.2M active micro-insurance policies issued.', rec: 'Launch emergency family health rider.' },
    { title: 'Digital Literacy Score', score: '95.2 / 100', trend: '+6.4%', reason: '1.8M workers operating multi-lingual AI voice assistant.', rec: 'Add regional voice dialects.' },
    { title: 'Emergency Response Score', score: '99.1 / 100', trend: '+1.5%', reason: '8.5 minute average response time for medical grants.', rec: 'Automate hospital direct payout API.' }
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* =========================================================================
          PRISTINE EXECUTIVE WHITEPAPER DOCUMENT PREVIEW
          ========================================================================= */}
      <div 
        ref={reportRef} 
        style={{ 
          background: '#FFFFFF', 
          color: '#0F172A', 
          padding: '3.5rem 4rem', 
          borderRadius: '12px', 
          border: '1px solid #E2E8F0', 
          boxShadow: '0 10px 40px rgba(30, 58, 138, 0.06)',
          fontFamily: "'Inter', -apple-system, sans-serif",
          lineHeight: 1.6
        }}
      >
        {/* DOCUMENT RUNNING HEADER */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.75rem', marginBottom: '2.5rem' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{ width: '36px', height: '36px', borderRadius: '8px', background: '#1E3A8A', color: '#FFFFFF', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Zap size={20} />
            </div>
            <div>
              <strong style={{ fontSize: '0.95rem', color: '#1E3A8A', textTransform: 'uppercase', letterSpacing: '0.05em', display: 'block', fontWeight: 900 }}>
                SAHAYATA PLATFORM FOR FINANCIAL INCLUSION
              </strong>
              <span style={{ fontSize: '0.7rem', color: '#475569', fontWeight: 700 }}>
                NATIONAL SOCIAL IMPACT & INFORMAL WORKFORCE EVALUATION
              </span>
            </div>
          </div>

          <div style={{ textAlign: 'right' }}>
            <span style={{ fontSize: '0.7rem', fontWeight: 800, color: '#0369a1', background: '#f0f9ff', padding: '3px 10px', borderRadius: '4px', border: '1px solid #bae6fd' }}>
              OFFICIAL IMPACT DOCUMENT
            </span>
            <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', marginTop: '3px' }}>
              REF: GOI-SAH-2026-NITI-8921
            </span>
          </div>
        </div>

        {/* COVER DOCUMENT BANNER */}
        <div style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '10px', padding: '2rem', marginBottom: '2.5rem' }}>
          <span style={{ fontSize: '0.75rem', fontWeight: 800, color: '#0284c7', textTransform: 'uppercase', letterSpacing: '0.1em' }}>
            NATIONAL IMPACT AUDIT REPORT
          </span>
          <h1 style={{ fontSize: '2.2rem', fontWeight: 900, color: '#0F172A', margin: '0.3rem 0 0.8rem 0', lineHeight: 1.15 }}>
            SAHAYATA IMPACT INTELLIGENCE REPORT 2026
          </h1>
          <p style={{ fontSize: '0.95rem', color: '#475569', margin: 0, maxWidth: '800px' }}>
            A formal whitepaper documenting the financial inclusion, credit velocity, insurance coverage, and employment placements delivered for 12.4M+ informal workers across 28 Indian States.
          </p>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', marginTop: '1.5rem', paddingTop: '1.25rem', borderTop: '1px solid #E2E8F0', fontSize: '0.8rem' }}>
            <div>
              <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', fontWeight: 700 }}>AUDIT PERIOD</span>
              <strong style={{ color: '#0F172A' }}>July 2026 (Last 30 Days)</strong>
            </div>

            <div>
              <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', fontWeight: 700 }}>DATE & TIME</span>
              <strong style={{ color: '#0F172A' }}>{new Date().toLocaleDateString()} IST</strong>
            </div>

            <div>
              <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', fontWeight: 700 }}>CLEARANCE</span>
              <strong style={{ color: '#0284c7' }}>Level 5 Super Admin</strong>
            </div>

            <div>
              <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', fontWeight: 700 }}>VERSION</span>
              <strong style={{ color: '#0F172A' }}>v4.8.2-SECURED</strong>
            </div>
          </div>
        </div>

        {/* TABLE OF CONTENTS */}
        <div style={{ marginBottom: '2.5rem', background: '#F1F5F9', padding: '1.25rem 1.5rem', borderRadius: '8px', borderLeft: '4px solid #1E3A8A' }}>
          <h3 style={{ margin: '0 0 0.75rem 0', fontSize: '1rem', color: '#1E3A8A', fontWeight: 800, textTransform: 'uppercase', letterSpacing: '0.05em', display: 'flex', alignItems: 'center', gap: '6px' }}>
            <BookOpen size={16} /> TABLE OF CONTENTS
          </h3>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.6rem', fontSize: '0.85rem' }}>
            {[
              '1. Executive Summary', '2. Worker Category Breakdown',
              '3. Sahayata Impact Scorecard', '4. Worker Success Stories',
              '5. AI Automated Insights (20+)'
            ].map((title, idx) => (
              <div key={idx} style={{ color: '#1E293B', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '6px' }}>
                <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: '#0284c7', display: 'inline-block' }} />
                <span>{title}</span>
              </div>
            ))}
          </div>
        </div>

        {/* =========================================================================
            SECTION 1: EXECUTIVE SUMMARY
            ========================================================================= */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#1E3A8A', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.4rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <FileText size={18} /> 1. EXECUTIVE SUMMARY: THE SAHAYATA IMPACT STORY
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '1rem', marginBottom: '1.5rem' }}>
            <div style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <span style={{ fontSize: '0.72rem', color: '#64748B', display: 'block', fontWeight: 700 }}>WORKERS JOINED</span>
              <strong style={{ fontSize: '1.4rem', color: '#1E3A8A' }}>12,450,890</strong>
              <span style={{ fontSize: '0.7rem', color: '#059669', display: 'block', marginTop: '2px', fontWeight: 700 }}>+18.4% MoM Growth</span>
            </div>

            <div style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <span style={{ fontSize: '0.72rem', color: '#64748B', display: 'block', fontWeight: 700 }}>FAMILIES BENEFITED</span>
              <strong style={{ fontSize: '1.4rem', color: '#0284c7' }}>49,803,560</strong>
              <span style={{ fontSize: '0.7rem', color: '#64748B', display: 'block', marginTop: '2px', fontWeight: 700 }}>4.0 Family Multiplier</span>
            </div>

            <div style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <span style={{ fontSize: '0.72rem', color: '#64748B', display: 'block', fontWeight: 700 }}>SCHEMES ACCESSED</span>
              <strong style={{ fontSize: '1.4rem', color: '#0D9488' }}>1,420 Active</strong>
              <span style={{ fontSize: '0.7rem', color: '#059669', display: 'block', marginTop: '2px', fontWeight: 700 }}>98.6% Success Rate</span>
            </div>

            <div style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
              <span style={{ fontSize: '0.72rem', color: '#64748B', display: 'block', fontWeight: 700 }}>LOANS APPROVED</span>
              <strong style={{ fontSize: '1.4rem', color: '#059669' }}>₹482.5 Cr</strong>
              <span style={{ fontSize: '0.7rem', color: '#059669', display: 'block', marginTop: '2px', fontWeight: 700 }}>99.2% Repayment Rate</span>
            </div>
          </div>

          <div style={{ background: '#F8FAFC', padding: '1.25rem', borderRadius: '8px', border: '1px solid #E2E8F0', lineHeight: 1.6, fontSize: '0.9rem', color: '#334155' }}>
            <p style={{ marginTop: 0 }}>
              Over the evaluated 30-day reporting period, Sahayata has delivered transformative social and financial inclusion for India's unorganized workforce. By combining multi-lingual AI voice guidance with UPI alternative credit scoring, <strong style={{ color: '#0F172A' }}>12.4M+ beneficiaries</strong> have unlocked working capital credit, micro-insurance, and government schemes previously inaccessible.
            </p>
            <p style={{ marginBottom: 0 }}>
              <strong style={{ color: '#1E3A8A' }}>Major Achievements:</strong> Disbursed ₹482.5 Crore in working capital sachet loans with a 99.2% on-time repayment rate, completed 118,500 verified job placements with partner fleets (Zomato, Swiggy, L&T), and resolved 1.8M multi-lingual AI queries with 99.4% accuracy.
            </p>
          </div>
        </div>

        {/* =========================================================================
            SECTION 2: WORKER IMPACT ANALYTICS TABLE
            ========================================================================= */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#1E3A8A', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.4rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Users size={18} /> 2. WORKER CATEGORY BREAKDOWN & SECTOR IMPACT
          </h2>

          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem', textAlign: 'left' }}>
              <thead>
                <tr style={{ background: '#1E3A8A', color: '#FFFFFF' }}>
                  <th style={{ padding: '9px 12px' }}>Worker Sector Category</th>
                  <th style={{ padding: '9px 12px' }}>Total Registered</th>
                  <th style={{ padding: '9px 12px' }}>Active Users</th>
                  <th style={{ padding: '9px 12px' }}>Verified Users</th>
                  <th style={{ padding: '9px 12px' }}>Avg Income Range</th>
                  <th style={{ padding: '9px 12px' }}>Growth %</th>
                  <th style={{ padding: '9px 12px' }}>Top Active States</th>
                </tr>
              </thead>
              <tbody>
                {workerCategories.map((row, idx) => (
                  <tr key={idx} style={{ background: idx % 2 === 0 ? '#F8FAFC' : '#FFFFFF', borderBottom: '1px solid #E2E8F0', color: '#334155' }}>
                    <td style={{ padding: '9px 12px', fontWeight: 700, color: '#0F172A' }}>{row.cat}</td>
                    <td style={{ padding: '9px 12px', color: '#0284c7', fontWeight: 800 }}>{row.reg}</td>
                    <td style={{ padding: '9px 12px' }}>{row.active}</td>
                    <td style={{ padding: '9px 12px', color: '#059669', fontWeight: 800 }}>{row.verified}</td>
                    <td style={{ padding: '9px 12px' }}>{row.income}</td>
                    <td style={{ padding: '9px 12px', color: '#059669', fontWeight: 800 }}>{row.growth}</td>
                    <td style={{ padding: '9px 12px' }}>{row.state}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* =========================================================================
            SECTION 3: SAHAYATA IMPACT SCORES
            ========================================================================= */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#1E3A8A', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.4rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Award size={18} /> 3. SAHAYATA OVERALL IMPACT SCORECARD (98.6 / 100)
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
            {impactScores.map((score, i) => (
              <div key={i} style={{ background: '#F8FAFC', padding: '1rem', borderRadius: '8px', border: '1px solid #E2E8F0' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.3rem' }}>
                  <span style={{ fontSize: '0.78rem', fontWeight: 800, color: '#1E3A8A' }}>{score.title}</span>
                  <span style={{ fontSize: '0.72rem', color: '#059669', fontWeight: 800 }}>{score.trend}</span>
                </div>
                <div style={{ fontSize: '1.5rem', fontWeight: 900, color: '#0284c7', marginBottom: '0.3rem' }}>
                  {score.score}
                </div>
                <p style={{ fontSize: '0.75rem', color: '#475569', margin: 0, lineHeight: 1.4 }}>
                  <strong>Reason:</strong> {score.reason}
                </p>
                <div style={{ fontSize: '0.72rem', color: '#0D9488', marginTop: '6px', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '4px' }}>
                  <Lightbulb size={12} /> Recommendation: {score.rec}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* =========================================================================
            SECTION 4: WORKER SUCCESS STORIES CARDS
            ========================================================================= */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#1E3A8A', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.4rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <HeartHandshake size={18} /> 4. WORKER SUCCESS STORIES (VERIFIED FIELD CASES)
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem' }}>
            {successStories.map((story, i) => (
              <div key={i} style={{ background: '#F8FAFC', border: '1px solid #E2E8F0', borderRadius: '8px', padding: '1.15rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
                  <strong style={{ fontSize: '0.98rem', color: '#0F172A' }}>{story.name}</strong>
                  <span style={{ fontSize: '0.68rem', fontWeight: 800, color: '#059669', background: '#ECFDF5', padding: '2px 8px', borderRadius: '4px', border: '1px solid #A7F3D0' }}>
                    {story.badge}
                  </span>
                </div>
                <span style={{ fontSize: '0.75rem', color: '#0284c7', fontWeight: 700, display: 'block', marginBottom: '0.75rem' }}>{story.role} • {story.city}</span>

                <div style={{ background: '#FEF2F2', padding: '0.55rem', borderRadius: '6px', marginBottom: '0.5rem', borderLeft: '3px solid #EF4444', fontSize: '0.75rem', color: '#991B1B' }}>
                  <strong>BEFORE SAHAYATA:</strong> {story.before}
                </div>

                <div style={{ background: '#ECFDF5', padding: '0.55rem', borderRadius: '6px', borderLeft: '3px solid #10B981', fontSize: '0.75rem', color: '#065F46' }}>
                  <strong>AFTER SAHAYATA:</strong> {story.after}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* =========================================================================
            SECTION 5: AI AUTOMATED INSIGHTS (20+ OBSERVATIONS)
            ========================================================================= */}
        <div style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#1E3A8A', borderBottom: '2px solid #1E3A8A', paddingBottom: '0.4rem', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Cpu size={18} /> 5. AI AUTOMATED INTELLIGENT INSIGHTS (20 OBSERVATIONS)
          </h2>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.6rem' }}>
            {[
              '1. Delivery partners showed the highest month-over-month growth rate (+22.4%).',
              '2. Women worker participation increased by 18.4% through targeted domestic worker drives.',
              '3. Multi-lingual voice assistant is preferred by 84% of first-time onboarded workers.',
              '4. Construction wage workers require additional insurance awareness campaigns in tier-3 cities.',
              '5. PM SVANidhi street vendor loan approvals increased by 31.2% following QR transaction scoring.',
              '6. Training course completion rate reached 92.4% for EV fleet operations certification.',
              '7. Gujarat registered the highest credit repayment rate (99.8% on-time repayment).',
              '8. Delhi NCR recorded the highest volume of AI voice conversations (420,000 queries).',
              '9. Average micro-loan processing speed accelerated to 1.4 minutes via automated ML pipeline.',
              '10. Emergency medical grants reduced debt distress for 1,420 beneficiary families by 82%.',
              '11. Domestic workers in Karnataka show 94% preference for sachet health insurance under ₹100/mo.',
              '12. Partner NGO awareness drives in UP added +34,000 daily wage worker enrollments.',
              '13. Voice queries in Hindi represent 58% of total AI conversations, followed by Marathi (22%).',
              '14. 98.4% of uploaded e-KYC documents passed automated optical character recognition.',
              '15. Peak AI server activity occurs between 7:00 PM and 9:30 PM IST daily.',
              '16. Platform 30-day worker retention rate reached a record high of 91.8%.',
              '17. Top requested upskilling skill: Solar Installation & EV Maintenance.',
              '18. Net Promoter Score (NPS) reached +78 among participating banks and NBFC lenders.',
              '19. Zero security breaches or unauthorized data access reported in past 30 days.',
              '20. 100% of disbursed loans are linked directly to verified Aadhaar-seeded bank accounts.'
            ].map((insight, idx) => (
              <div key={idx} style={{ background: '#F8FAFC', padding: '0.6rem 0.85rem', borderRadius: '4px', borderLeft: '3px solid #0284c7', fontSize: '0.78rem', color: '#334155' }}>
                {insight}
              </div>
            ))}
          </div>
        </div>

        {/* DOCUMENT CLOSING FOOTER */}
        <div style={{ borderTop: '2px solid #1E3A8A', paddingTop: '1.5rem', marginTop: '2rem', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div>
            <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748B' }}>ISSUING AUTHORITY</div>
            <strong style={{ fontSize: '0.95rem', color: '#1E3A8A', display: 'block' }}>SAHAYATA AI INTELLIGENCE ENGINE</strong>
            <p style={{ fontSize: '0.82rem', color: '#0284c7', margin: '3px 0 0 0', fontStyle: 'italic', fontWeight: 600 }}>
              "Every number in this report represents a worker whose life moved one step closer to financial security through Sahayata."
            </p>
          </div>

          <div style={{ display: 'flex', gap: '1rem', alignItems: 'center' }}>
            <div style={{ textAlign: 'right' }}>
              <span style={{ fontSize: '0.68rem', color: '#64748B', display: 'block', fontWeight: 700 }}>NATIONAL COVERAGE</span>
              <strong style={{ fontSize: '1.3rem', color: '#059669' }}>28 STATES & UTs</strong>
            </div>

            <div style={{ width: '50px', height: '50px', border: '2px solid #1E3A8A', borderRadius: '6px', padding: '3px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <QrCode size={40} color="#1E3A8A" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
