import { useMemo, useState } from "react";
import { ChevronDown, CircleHelp, FileCheck2, LockKeyhole, MessageCircleQuestion, ShieldAlert, WalletCards } from "lucide-react";
import "./HelpCenter.css";

const FAQS = [
  { c: "start", en: ["What is Sahayata?", "Sahayata is a financial-support portal for gig workers, delivery partners, street vendors and daily wage earners. It brings eligibility checks, loan applications, UPI insights, KYC tracking and repayment guidance together."], hi: ["Sahayata kya hai?", "Sahayata gig workers, delivery partners, street vendors aur daily wage earners ke liye financial-support portal hai. Yahan eligibility check, loan application, UPI insights, KYC tracking aur repayment guidance ek jagah milti hai."] },
  { c: "start", en: ["Who can apply?", "Street vendors, delivery partners, gig workers, construction labourers and other daily-income workers can apply. Final eligibility depends on the lender review and applicable rules."], hi: ["Kaun apply kar sakta hai?", "Street vendors, delivery partners, gig workers, construction labour aur dusre daily-income workers apply kar sakte hain. Final eligibility lender ke review aur applicable rules par depend karti hai."] },
  { c: "start", en: ["How do I create an account?", "Use Register in the header, enter your name, mobile number and password, then log in. After login you can submit KYC documents and view their status."], hi: ["Account kaise banau?", "Header mein Register par click karein, apna naam, mobile number aur password enter karein. Login ke baad aap KYC documents upload aur unka status dekh sakte hain."] },
  { c: "loan", en: ["Is the eligibility calculator a final loan approval?", "No. It is an indicative estimate. The final sanctioned amount depends on KYC, cash-flow signals, fraud checks and the lender/NBFC review."], hi: ["Kya eligibility calculator ka result final loan approval hai?", "Nahi. Yeh sirf indicative estimate hai. Final sanctioned amount KYC, cash-flow signals, fraud checks aur lender/NBFC review ke baad decide hota hai."] },
  { c: "loan", en: ["What happens after I submit an application?", "The timeline shows Submitted, e-KYC verification, NBFC review, Bank sanction and Disbursal. Your current stage is shown in the application tracker."], hi: ["Application submit karne ke baad kya hota hai?", "Application timeline mein Submitted, e-KYC verification, NBFC review, Bank sanction aur Disbursal stages dikhte hain. Current stage tracker mein visible rahega."] },
  { c: "loan", en: ["How much loan can I get?", "The app may show working-capital estimates from ₹5,000 to ₹50,000. The actual sanctioned amount is decided by the lender after review."], hi: ["Kitne amount ka loan mil sakta hai?", "App mein working-capital estimate ₹5,000 se ₹50,000 tak dikh sakta hai. Actual sanctioned amount lender review ke baad decide karta hai."] },
  { c: "kyc", en: ["Which KYC documents can I upload?", "You can upload an Aadhaar card, PAN card, e-Shram card or bank statement. PDF, JPG and PNG are accepted; each file must be 5 MB or smaller."], hi: ["KYC ke liye kaunse documents upload kar sakte hain?", "Aadhaar card, PAN card, e-Shram card ya bank statement upload kiya ja sakta hai. PDF, JPG aur PNG accepted hain; har file maximum 5 MB honi chahiye."] },
  { c: "kyc", en: ["Why does my document show Pending review?", "Your upload was received successfully and is waiting in the verification queue. Pending review means an approve or reject decision has not been completed yet."], hi: ["Document ka status Pending review kyun dikha raha hai?", "Aapka upload successfully receive ho chuka hai aur verification queue mein hai. Pending review ka matlab approval ya rejection abhi complete nahi hua hai."] },
  { c: "upi", en: ["How does the UPI credit insight work?", "With consent, transaction patterns such as throughput, consistency, repeat customers and unusual activity can be analysed as alternate credit signals. It is not a replacement for a lender decision."], hi: ["UPI credit insight kaise kaam karta hai?", "Consent ke saath daily throughput, consistency, repeat customers aur unusual activity jaise transaction patterns analyse hote hain. Yeh lender ke final decision ka replacement nahi hai."] },
  { c: "upi", en: ["What repayment options are available?", "The app explains daily fixed, daily flexible collection-based and monthly EMI options. The lender's approved mandate and loan terms are always final."], hi: ["Repayment ke kaunse options hain?", "App daily fixed, collection-based daily flexible aur monthly EMI options explain karta hai. Lender ka approved mandate aur loan terms hamesha final hote hain."] },
  { c: "security", en: ["Should I share my OTP or UPI PIN?", "Never. Enter an OTP only yourself on the official app or website screen. No Sahayata staff member, agent or assistant should ask you to disclose an OTP, PIN or password."], hi: ["Kya mujhe OTP ya UPI PIN share karna chahiye?", "Kabhi nahi. OTP sirf official app ya website ke verification screen par khud enter karein. Koi bhi Sahayata staff member, agent ya assistant aapse OTP, PIN ya password nahi maangega."] },
  { c: "security", en: ["What should I do if I receive a suspicious call or link?", "Do not open the link or share any OTP, PIN, password or document. Leave the page, change your password if needed and use only verified official channels."], hi: ["Mujhe suspicious call ya link mila hai, kya karu?", "Link open na karein aur koi OTP, PIN, password ya document share na karein. Page se bahar niklein, zaroorat ho to password change karein aur sirf verified official channels ka use karein."] },
];
const GUJARATI_FAQS = [
  ["Sahayata shu chhe?", "Sahayata gig workers, delivery partners, street vendors ane rojni aavak dharavta kamdaro mate financial-support portal chhe. Tema eligibility check, loan application, UPI insights, KYC tracking ane repayment guidance male chhe."],
  ["Kon apply kari shake?", "Street vendors, delivery partners, gig workers, construction labour ane anya rojni aavak dharavta workers apply kari shake chhe. Final eligibility lender review ane lagu niyamo par aadhar rakhe chhe."],
  ["Account kevi rite banavu?", "Header ma Register par click karo, naam, mobile number ane password bharo. Login pachi tame KYC documents upload ane tenu status joi shako chho."],
  ["Shu eligibility calculator final loan approval chhe?", "Na. Aa fakt indicative estimate chhe. Final sanctioned amount KYC, cash-flow signals, fraud checks ane lender/NBFC review pachi nakki thaye chhe."],
  ["Application submit karya pachi shu thaye?", "Timeline ma Submitted, e-KYC verification, NBFC review, Bank sanction ane Disbursal stages dekhase. Current stage application tracker ma jovama aavse."],
  ["Ketli loan mali shake?", "App ma working-capital estimate ₹5,000 thi ₹50,000 sudhi dekhai shake chhe. Actual sanctioned amount lender review pachi nakki kare chhe."],
  ["Kaya KYC documents upload kari shaku?", "Aadhaar card, PAN card, e-Shram card athva bank statement upload kari shako chho. PDF, JPG ane PNG accepted chhe; darek file 5 MB athva ochhi hovi joie."],
  ["Document nu status Pending review kem dekhay chhe?", "Tamaro upload safaltapurvak receive thayo chhe ane verification queue ma chhe. Pending review etle approval athva rejection haju puro thayo nathi."],
  ["UPI credit insight kevi rite kaam kare chhe?", "Consent sathe daily throughput, consistency, repeat customers ane unusual activity jeva transaction patterns analyse thay chhe. Aa lender na final decision no replacement nathi."],
  ["Repayment na kaya options chhe?", "App daily fixed, collection-based daily flexible ane monthly EMI options samjave chhe. Lender nu approved mandate ane loan terms hamesha final hoy chhe."],
  ["Shu OTP ke UPI PIN share karvu joie?", "Kyarey nahi. OTP fakt official app athva website na verification screen par pote enter karo. Koi pan Sahayata staff, agent ke assistant OTP, PIN athva password nahi maange."],
  ["Suspicious call athva link male to shu karvu?", "Link kholo nahi ane OTP, PIN, password athva document share karo nahi. Page thi bahar niklo, jarur hoy to password badlo ane fakt verified official channels no upyog karo."],
];
const HINDI_FAQS = [
  ["सहायता क्या है?", "सहायता गिग वर्कर्स, डिलीवरी पार्टनर्स, स्ट्रीट वेंडर्स और दैनिक वेतन पाने वाले श्रमिकों के लिए वित्तीय सहायता पोर्टल है। यहाँ पात्रता जाँच, ऋण आवेदन, UPI जानकारी, KYC ट्रैकिंग और पुनर्भुगतान मार्गदर्शन एक जगह मिलता है।"],
  ["कौन आवेदन कर सकता है?", "स्ट्रीट वेंडर्स, डिलीवरी पार्टनर्स, गिग वर्कर्स, निर्माण श्रमिक और अन्य दैनिक आय वाले श्रमिक आवेदन कर सकते हैं। अंतिम पात्रता ऋणदाता की समीक्षा और लागू नियमों पर निर्भर करती है।"],
  ["अकाउंट कैसे बनाऊँ?", "हेडर में Register पर क्लिक करें, अपना नाम, मोबाइल नंबर और पासवर्ड भरें। लॉगिन के बाद आप KYC दस्तावेज़ अपलोड और उनका स्टेटस देख सकते हैं।"],
  ["क्या पात्रता कैलकुलेटर का परिणाम अंतिम ऋण स्वीकृति है?", "नहीं। यह केवल एक अनुमान है। अंतिम स्वीकृत राशि KYC, कैश-फ्लो संकेत, फ्रॉड जाँच और ऋणदाता/NBFC की समीक्षा के बाद तय होती है।"],
  ["आवेदन जमा करने के बाद क्या होता है?", "टाइमलाइन में Submitted, e-KYC verification, NBFC review, Bank sanction और Disbursal चरण दिखते हैं। वर्तमान चरण एप्लिकेशन ट्रैकर में दिखाई देगा।"],
  ["कितने का ऋण मिल सकता है?", "ऐप में कार्यशील पूंजी का अनुमान ₹5,000 से ₹50,000 तक दिख सकता है। वास्तविक स्वीकृत राशि ऋणदाता समीक्षा के बाद तय करता है।"],
  ["KYC के लिए कौन से दस्तावेज़ अपलोड कर सकते हैं?", "आधार कार्ड, PAN कार्ड, e-Shram कार्ड या बैंक स्टेटमेंट अपलोड किया जा सकता है। PDF, JPG और PNG स्वीकार हैं; हर फ़ाइल अधिकतम 5 MB होनी चाहिए।"],
  ["दस्तावेज़ का स्टेटस Pending review क्यों दिख रहा है?", "आपका अपलोड सफलतापूर्वक प्राप्त हो गया है और सत्यापन कतार में है। Pending review का अर्थ है कि स्वीकृति या अस्वीकृति अभी पूरी नहीं हुई है।"],
  ["UPI क्रेडिट इनसाइट कैसे काम करता है?", "सहमति के साथ दैनिक लेनदेन, निरंतरता, दोबारा आने वाले ग्राहक और असामान्य गतिविधि जैसे पैटर्न का विश्लेषण होता है। यह ऋणदाता के अंतिम निर्णय का विकल्प नहीं है।"],
  ["पुनर्भुगतान के कौन से विकल्प हैं?", "ऐप दैनिक निश्चित, कलेक्शन आधारित दैनिक फ्लेक्सिबल और मासिक EMI विकल्प समझाता है। ऋणदाता का स्वीकृत मैंडेट और ऋण शर्तें हमेशा अंतिम होंगी।"],
  ["क्या मुझे OTP या UPI PIN शेयर करना चाहिए?", "कभी नहीं। OTP केवल आधिकारिक ऐप या वेबसाइट की वेरिफिकेशन स्क्रीन पर स्वयं दर्ज करें। कोई भी सहायता स्टाफ, एजेंट या असिस्टेंट OTP, PIN या पासवर्ड नहीं माँगेगा।"],
  ["संदिग्ध कॉल या लिंक मिले तो क्या करूँ?", "लिंक न खोलें और OTP, PIN, पासवर्ड या दस्तावेज़ शेयर न करें। पेज से बाहर निकलें, ज़रूरत हो तो पासवर्ड बदलें और केवल सत्यापित आधिकारिक चैनलों का उपयोग करें।"],
];
const NATIVE_GUJARATI_FAQS = [
  ["સહાયતા શું છે?", "સહાયતા ગિગ વર્કર્સ, ડિલિવરી પાર્ટનર્સ, સ્ટ્રીટ વેન્ડર્સ અને દૈનિક વેતન મેળવનારા શ્રમિકો માટેનું નાણાકીય સહાય પોર્ટલ છે. અહીં પાત્રતા તપાસ, લોન અરજી, UPI માહિતી, KYC ટ્રેકિંગ અને ચુકવણી માર્ગદર્શન એક જ જગ્યાએ મળે છે."],
  ["કોણ અરજી કરી શકે?", "સ્ટ્રીટ વેન્ડર્સ, ડિલિવરી પાર્ટનર્સ, ગિગ વર્કર્સ, બાંધકામ શ્રમિકો અને અન્ય દૈનિક આવક ધરાવતા શ્રમિકો અરજી કરી શકે છે. અંતિમ પાત્રતા ધિરાણકર્તાની સમીક્ષા અને લાગુ નિયમો પર આધાર રાખે છે."],
  ["એકાઉન્ટ કેવી રીતે બનાવું?", "હેડરમાં Register પર ક્લિક કરો, તમારું નામ, મોબાઇલ નંબર અને પાસવર્ડ ભરો. લૉગિન પછી તમે KYC દસ્તાવેજો અપલોડ અને તેમનું સ્ટેટસ જોઈ શકો છો."],
  ["શું પાત્રતા કેલ્ક્યુલેટરનું પરિણામ અંતિમ લોન મંજૂરી છે?", "ના. આ માત્ર એક અંદાજ છે. અંતિમ મંજૂર રકમ KYC, કેશ-ફ્લો સંકેતો, ફ્રોડ તપાસ અને ધિરાણકર્તા/NBFC ની સમીક્ષા પછી નક્કી થાય છે."],
  ["અરજી સબમિટ કર્યા પછી શું થાય છે?", "ટાઇમલાઇનમાં Submitted, e-KYC verification, NBFC review, Bank sanction અને Disbursal તબક્કા દેખાય છે. હાલનો તબક્કો એપ્લિકેશન ટ્રેકરમાં દેખાશે."],
  ["કેટલી લોન મળી શકે?", "એપમાં કાર્યકારી મૂડીનો અંદાજ ₹5,000 થી ₹50,000 સુધી દેખાઈ શકે છે. વાસ્તવિક મંજૂર રકમ ધિરાણકર્તાની સમીક્ષા પછી નક્કી થાય છે."],
  ["KYC માટે કયા દસ્તાવેજો અપલોડ કરી શકાય?", "આધાર કાર્ડ, PAN કાર્ડ, e-Shram કાર્ડ અથવા બેંક સ્ટેટમેન્ટ અપલોડ કરી શકાય છે. PDF, JPG અને PNG સ્વીકાર્ય છે; દરેક ફાઇલ મહત્તમ 5 MB હોવી જોઈએ."],
  ["દસ્તાવેજનું સ્ટેટસ Pending review કેમ દેખાય છે?", "તમારું અપલોડ સફળતાપૂર્વક પ્રાપ્ત થયું છે અને વેરિફિકેશન કતારમાં છે. Pending review નો અર્થ છે કે મંજૂરી અથવા અસ્વીકૃતિ હજી પૂર્ણ થઈ નથી."],
  ["UPI ક્રેડિટ ઇનસાઇટ કેવી રીતે કામ કરે છે?", "સંમતિ સાથે દૈનિક લેવડદેવડ, સાતત્ય, ફરી આવતા ગ્રાહકો અને અસામાન્ય પ્રવૃત્તિ જેવા પેટર્નનું વિશ્લેષણ થાય છે. આ ધિરાણકર્તાના અંતિમ નિર્ણયનો વિકલ્પ નથી."],
  ["ચુકવણીના કયા વિકલ્પો છે?", "એપ દૈનિક નિશ્ચિત, કલેક્શન આધારિત દૈનિક ફ્લેક્સિબલ અને માસિક EMI વિકલ્પ સમજાવે છે. ધિરાણકર્તાનો મંજૂર મેન્ડેટ અને લોન શરતો હંમેશા અંતિમ રહેશે."],
  ["શું OTP અથવા UPI PIN શેર કરવો જોઈએ?", "ક્યારેય નહીં. OTP ફક્ત અધિકૃત એપ અથવા વેબસાઇટની વેરિફિકેશન સ્ક્રીન પર જાતે દાખલ કરો. કોઈ પણ સહાયતા સ્ટાફ, એજન્ટ કે અસિસ્ટન્ટ OTP, PIN અથવા પાસવર્ડ માંગશે નહીં."],
  ["શંકાસ્પદ કોલ અથવા લિંક મળે તો શું કરવું?", "લિંક ખોલશો નહીં અને OTP, PIN, પાસવર્ડ અથવા દસ્તાવેજ શેર કરશો નહીં. પેજમાંથી બહાર નીકળો, જરૂર હોય તો પાસવર્ડ બદલો અને માત્ર ચકાસેલી અધિકૃત ચેનલોનો ઉપયોગ કરો."],
];
FAQS.forEach((item, index) => { item.hi = HINDI_FAQS[index]; item.gu = NATIVE_GUJARATI_FAQS[index]; });
const COPY = { en: { kicker: "Help & Support Center", title: "Clear guidance at every step.", sub: "Answers about registration, KYC, loans, UPI insights, repayments and account security.", search: "Search your question…", all: "All topics", topics: "Browse by topic", faqs: "Frequently asked questions", help: "How can we help?", answers: "answers", noTitle: "No answer found", noText: "Try another keyword or select all topics.", security: "Safety reminder: never share your OTP", securityText: "Sahayata staff, support agents and voice assistants will never ask for your OTP, UPI PIN or password.", cards: [["KYC support", "Documents, file limits and verification status."], ["Loan guidance", "Eligibility, application stages and repayments."], ["Stay secure", "Protect your OTP, UPI PIN and account."]] }, hi: { kicker: "Help aur Support Center", title: "Har step par saaf guidance.", sub: "Registration, KYC, loan, UPI insights, repayment aur account security ke answers ek jagah.", search: "Apna sawaal search karein…", all: "Sabhi topics", topics: "Topic choose karein", faqs: "Aksar pooche jaane wale sawaal", help: "Hum kaise madad karein?", answers: "answers", noTitle: "Koi answer nahi mila", noText: "Dusra keyword try karein ya sabhi topics choose karein.", security: "Safety reminder: OTP kabhi share mat karein", securityText: "Sahayata staff, support agent aur voice assistant kabhi bhi OTP, UPI PIN ya password nahi maangenge.", cards: [["KYC support", "Documents, file limit aur verification status."], ["Loan guidance", "Eligibility, application stages aur repayment."], ["Secure rahein", "OTP, UPI PIN aur account ko secure rakhein."]] }, gu: { kicker: "Help ane Support Center", title: "Darek step par spashta margdarshan.", sub: "Registration, KYC, loan, UPI insights, repayment ane account security na jawab ekaj jagyae.", search: "Tamaro prashna shodho…", all: "Badha topics", topics: "Topic pasand karo", faqs: "Vaaramvaar puchhata prashno", help: "Ame kevi rite madad kariye?", answers: "jawabo", noTitle: "Koi jawab malyo nahi", noText: "Bijo keyword try karo athva badha topics pasand karo.", security: "Safety reminder: OTP kyarey share na karo", securityText: "Sahayata staff, support agent ane voice assistant tamari pase OTP, UPI PIN athva password kyarey nahi mange.", cards: [["KYC support", "Documents, file limit ane verification status."], ["Loan guidance", "Eligibility, application stages ane repayment."], ["Surakshit raho", "OTP, UPI PIN ane account surakshit rakho."]] } };
const TOPICS = { en: { start: "Getting started", loan: "Eligibility & loans", kyc: "KYC & documents", upi: "UPI & repayment", security: "Security" }, hi: { start: "Shuruaat", loan: "Eligibility aur loan", kyc: "KYC aur documents", upi: "UPI aur repayment", security: "Security" }, gu: { start: "Shuruaat", loan: "Eligibility ane loan", kyc: "KYC ane documents", upi: "UPI ane repayment", security: "Security" } };
const ICONS = [FileCheck2, WalletCards, LockKeyhole];
COPY.hi = { ...COPY.hi, kicker: "सहायता और सपोर्ट सेंटर", title: "हर कदम पर स्पष्ट मार्गदर्शन।", sub: "रजिस्ट्रेशन, KYC, लोन, UPI जानकारी, पुनर्भुगतान और अकाउंट सुरक्षा के जवाब एक जगह।", search: "अपना सवाल खोजें…", all: "सभी विषय", topics: "विषय चुनें", faqs: "अक्सर पूछे जाने वाले सवाल", help: "हम आपकी कैसे मदद करें?", answers: "जवाब", noTitle: "कोई जवाब नहीं मिला", noText: "दूसरा कीवर्ड आज़माएँ या सभी विषय चुनें।", security: "सुरक्षा रिमाइंडर: OTP कभी शेयर न करें", securityText: "सहायता स्टाफ, सपोर्ट एजेंट और वॉइस असिस्टेंट कभी भी OTP, UPI PIN या पासवर्ड नहीं माँगेंगे।", cards: [["KYC सहायता", "दस्तावेज़, फ़ाइल सीमा और वेरिफिकेशन स्टेटस।"], ["लोन मार्गदर्शन", "पात्रता, आवेदन चरण और पुनर्भुगतान।"], ["सुरक्षित रहें", "OTP, UPI PIN और अकाउंट को सुरक्षित रखें।"]] };
COPY.gu = { ...COPY.gu, kicker: "સહાયતા અને સપોર્ટ સેન્ટર", title: "દરેક પગલે સ્પષ્ટ માર્ગદર્શન.", sub: "રજિસ્ટ્રેશન, KYC, લોન, UPI માહિતી, ચુકવણી અને એકાઉન્ટ સુરક્ષાના જવાબ એક જ જગ્યાએ.", search: "તમારો પ્રશ્ન શોધો…", all: "બધા વિષયો", topics: "વિષય પસંદ કરો", faqs: "વારંવાર પૂછાતા પ્રશ્નો", help: "અમે તમારી કેવી રીતે મદદ કરીએ?", answers: "જવાબો", noTitle: "કોઈ જવાબ મળ્યો નથી", noText: "બીજો કીવર્ડ અજમાવો અથવા બધા વિષયો પસંદ કરો.", security: "સુરક્ષા રિમાઇન્ડર: OTP ક્યારેય શેર ન કરો", securityText: "સહાયતા સ્ટાફ, સપોર્ટ એજન્ટ અને વોઇસ અસિસ્ટન્ટ ક્યારેય OTP, UPI PIN અથવા પાસવર્ડ માંગશે નહીં.", cards: [["KYC સહાય", "દસ્તાવેજો, ફાઇલ મર્યાદા અને વેરિફિકેશન સ્ટેટસ."], ["લોન માર્ગદર્શન", "પાત્રતા, અરજીના તબક્કા અને ચુકવણી."], ["સુરક્ષિત રહો", "OTP, UPI PIN અને એકાઉન્ટ સુરક્ષિત રાખો."]] };
TOPICS.hi = { start: "शुरुआत", loan: "पात्रता और लोन", kyc: "KYC और दस्तावेज़", upi: "UPI और पुनर्भुगतान", security: "सुरक्षा" };
TOPICS.gu = { start: "શરૂઆત", loan: "પાત્રતા અને લોન", kyc: "KYC અને દસ્તાવેજો", upi: "UPI અને ચુકવણી", security: "સુરક્ષા" };
export default function HelpCenter({ lang = "en" }) { const language = ["hi", "gu"].includes(lang) ? lang : "en"; const copy = COPY[language]; const topics = TOPICS[language]; const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [open, setOpen] = useState(null); const visible = useMemo(() => FAQS.filter((item) => (category === "all" || item.c === category) && `${item[language][0]} ${item[language][1]}`.toLowerCase().includes(query.toLowerCase().trim())), [category, language, query]); return <main className="help-page"><section className="help-hero"><div className="help-hero-inner"><div className="help-kicker"><CircleHelp size={16} />{copy.kicker}</div><h1>{copy.title}</h1><p>{copy.sub}</p><label className="help-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={copy.search} aria-label={copy.search} /></label></div></section><section className="help-content"><div className="help-quick-grid">{copy.cards.map(([title, text], index) => { const Icon = ICONS[index]; return <article key={title}><Icon /><h3>{title}</h3><p>{text}</p></article>; })}</div><div className="help-layout"><aside className="help-sidebar"><h3>{copy.topics}</h3><button className={category === "all" ? "active" : ""} onClick={() => setCategory("all")}>{copy.all}<span>{FAQS.length}</span></button>{Object.entries(topics).map(([key, label]) => <button className={category === key ? "active" : ""} key={key} onClick={() => setCategory(key)}>{label}<span>{FAQS.filter((faq) => faq.c === key).length}</span></button>)}</aside><div className="faq-panel"><div className="faq-panel-head"><div><div className="eyebrow">{copy.faqs}</div><h2>{category === "all" ? copy.help : topics[category]}</h2></div><span>{visible.length} {copy.answers}</span></div>{visible.length ? visible.map((item) => { const id = item.c + item.en[0]; const isOpen = open === id; return <article className={`faq-item${isOpen ? " open" : ""}`} key={id}><button onClick={() => setOpen(isOpen ? null : id)} aria-expanded={isOpen}><span><small>{topics[item.c]}</small>{item[language][0]}</span><ChevronDown size={19} /></button>{isOpen && <p>{item[language][1]}</p>}</article>; }) : <div className="faq-empty"><MessageCircleQuestion size={28} /><h3>{copy.noTitle}</h3><p>{copy.noText}</p></div>}</div></div><div className="help-security"><ShieldAlert size={24} /><div><h3>{copy.security}</h3><p>{copy.securityText}</p></div></div></section></main>; }
